version: '3.8'

services:
  dredge:
    build: .
    container_name: dredge
    user: root
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      - ./tests:/app/tests
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
